export default {
  business: {
    getWechatSign: '/api/getWechatSign',
    getOpenId: '/api/getInfo',
    getLuck: '/api/getLuck',
    addInfo: '/api/addInfo',
    getShareCount: '/api/getShareCount',
    addShare: '/api/addShare',
    getSelfInfo: '/api/getSelfInfo',
    getMyAwards: '/api/getMyAwards',
    getAwardsWithMobileShop: '/api/getAwardsWithMobileShop',
    verifyAward: '/api/verifyAward/',
  },
  wx: {
    getToken: '/wx/cgi-bin/token',
    getTicket: '/wx/cgi-bin/ticket/getticket',
  },
  newyear: {
    getWechatSign: '/api/getWechatSign',
    getOpenId: '/api/newYear/getInfo',
    getShareCount: '/api/newYear/getShareCount',
    addShare: '/api/newYear/addShare',
    addCard: '/api/newYear/addCard',
    getCard: '/api/newYear/getCard',
  },
  building: {
    getOpenId: '/api/building/getInfo',
    getCards: '/api/building/getCards',
    getCount: '/api/building/getCount',
    getSelfInfo: '/api/building/getSelfInfo',
    draw: '/api/building/draw',
    send: '/api/building/send',
  },
  answer: {
    getOpenId: '/api/answer/getInfo',
    getSelfInfo: '/api/answer/getSelfInfo',
    getScoreToday: '/api/answer/getScoreToday',
    score: "/api/answer/finishQuestion",
  },
};
